import type { GatewayBrowserClient } from "../gateway.ts";
import type { ChannelsStatusSnapshot } from "../types.ts";

export type ChannelsState = {
  client: GatewayBrowserClient | null;
  connected: boolean;
  setupWizardSessionId?: string | null;
  setupWizardStep?: import("../types.ts").WizardStep | null;
  setupWizardStatus?: string | null;
  setupWizardError?: string | null;
  channelsLoading: boolean;
  channelsSnapshot: ChannelsStatusSnapshot | null;
  channelsError: string | null;
  channelsLastSuccess: number | null;
  channelsBusyKey?: string | null;
  channelsActionMessage?: string | null;
  channelsLoginQrDataUrl?: string | null;
  channelsLoginConnected?: boolean | null;
  channelsSetupLoading?: boolean;
  channelsSetupSubmitting?: boolean;
  channelsSetupSessionId?: string | null;
  channelsSetupStep?: import("../types.ts").WizardStep | null;
  channelsSetupStatus?: string | null;
  channelsSetupError?: string | null;
  channelsSetupDraftText?: string;
  channelsSetupDraftConfirm?: boolean;
  channelsSetupDraftSelectIndex?: number;
  channelsSetupDraftMultiIndexes?: number[];
  channelsSetupChannelId?: string | null;
};
