/* @vitest-environment jsdom */

import { render } from "lit";
import { describe, expect, it, vi } from "vitest";
import type { AlisioBootstrapState, NativeShellState } from "../types.ts";
import { renderSetup } from "./setup.ts";

function createNativeShellState(): NativeShellState {
  return {
    platform: "macos",
    launchAtLogin: true,
    permissions: {
      notifications: true,
      appleScript: false,
      accessibility: true,
      screenRecording: false,
      microphone: true,
      speechRecognition: false,
      camera: true,
      location: false,
    },
    voiceWake: {
      supported: true,
      enabled: false,
      talkEnabled: false,
      triggers: ["Hey Alisio"],
    },
    logsPath: "~/Library/Logs/Alisio",
  };
}

function createBootstrapAccount(): NonNullable<AlisioBootstrapState["account"]> {
  return {
    profile: {
      username: "nuno",
      displayName: "Nuno",
      email: "nuno@example.com",
      avatarLabel: "N",
      joinedAt: "2026-04-01T00:00:00.000Z",
      plan: "free",
    },
    preferences: {
      language: "pt-PT" as const,
      theme: "dark" as const,
    },
    session: {
      state: "signed_in" as const,
      profileCompleted: true,
    },
    devices: [],
  };
}

function createReadyBootstrap(overrides: Partial<AlisioBootstrapState> = {}): AlisioBootstrapState {
  return {
    connectionRequired: false,
    wizardRequired: false,
    wizardRunning: false,
    providerReady: true,
    accountReady: true,
    startupState: "ready",
    organizationState: { mode: "none" },
    connectorSummary: {
      total: 0,
      ready: 0,
      connected: 0,
      needsReconnect: 0,
      inReview: 0,
      unavailable: 0,
      available: 0,
    },
    nextStep: "ready",
    account: createBootstrapAccount(),
    ai: {
      provider: "openai",
      status: "connected",
    },
    organization: { mode: "none" },
    connectors: {
      catalog: [],
      authorizations: [],
      summary: {
        total: 0,
        ready: 0,
        connected: 0,
        needsReconnect: 0,
        inReview: 0,
        unavailable: 0,
        available: 0,
      },
    },
    wizard: { running: false, sessionId: null },
    models: { total: 0, defaultProvider: "openai", providers: [] },
    ...overrides,
  };
}

describe("setup view", () => {
  it("renders the web-first setup flow and key steps", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: false,
        lastError: "Runtime unavailable",
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: null,
        startupLoading: false,
        startupError: null,
        startupBootstrap: {
          basePath: "/",
          controlUrl: "ws://127.0.0.1:18789/",
          startupState: "signed_out",
          account: {
            username: "nuno",
            displayName: "Nuno",
            email: "nuno@example.com",
            avatarLabel: "N",
            plan: "free",
          },
          ai: null,
        },
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: "runtime",
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "nuno@example.com",
        authPassword: "password123",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "none" },
        organizationDraftMode: "create",
        organizationName: "",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [
          {
            id: "github",
            title: "GitHub",
            providerLabel: "GitHub",
            category: "development",
            connectLabel: "Connect with GitHub",
            summary: "Repositories and pull requests.",
            availability: "ready",
            scopes: ["repo"],
          },
        ],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("Welcome to Alisio");
    expect(container.textContent).toContain("Set up your personal agent.");
    expect(container.textContent).toContain("connect OpenAI");
    expect(container.textContent).toContain("Create your account");
    expect(container.textContent).toContain("Email");
    expect(container.textContent).toContain("Password");
    expect(container.textContent).toContain("Use the email you want to use to sign in to Alisio.");
    expect(container.textContent).toContain("Reconnect Alisio");
    expect(container.textContent).toContain("Alisio should connect automatically on this host.");
  });

  it("shows the ready step instead of organization once onboarding is already complete", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: true,
        lastError: null,
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: createReadyBootstrap({ nextStep: "organization" }),
        startupLoading: false,
        startupError: null,
        startupBootstrap: null,
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: null,
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "",
        authPassword: "",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "none" },
        organizationDraftMode: "create",
        organizationName: "",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("You are ready");
    expect(container.textContent).not.toContain("Create organization");
  });

  it("ignores a stale runtime step once setup is already ready", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: true,
        lastError: null,
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: createReadyBootstrap(),
        startupLoading: false,
        startupError: null,
        startupBootstrap: null,
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: "runtime",
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "",
        authPassword: "",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "none" },
        organizationDraftMode: "create",
        organizationName: "",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("You are ready");
    expect(container.textContent).not.toContain("Connect OpenAI");
  });

  it("shows the ready step instead of connectors once onboarding is already complete", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: true,
        lastError: null,
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: createReadyBootstrap({
          nextStep: "connectors",
          organizationState: { mode: "owner", organizationName: "Team" },
          organization: { mode: "owner", organizationName: "Team" },
          connectorSummary: {
            total: 1,
            ready: 1,
            connected: 0,
            needsReconnect: 0,
            inReview: 0,
            unavailable: 0,
            available: 1,
          },
          connectors: {
            catalog: [],
            authorizations: [],
            summary: {
              total: 1,
              ready: 1,
              connected: 0,
              needsReconnect: 0,
              inReview: 0,
              unavailable: 0,
              available: 1,
            },
          },
        }),
        startupLoading: false,
        startupError: null,
        startupBootstrap: null,
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: null,
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "",
        authPassword: "",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "owner", organizationName: "Team" },
        organizationDraftMode: "create",
        organizationName: "Team",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [
          {
            id: "github",
            title: "GitHub",
            providerLabel: "GitHub",
            category: "development",
            connectLabel: "Connect with GitHub",
            summary: "Repositories and pull requests.",
            availability: "ready",
            scopes: ["repo"],
          },
        ],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("You are ready");
    expect(container.textContent).not.toContain("GitHub");
  });

  it("shows the ready step instead of permissions once onboarding is already complete", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: true,
        lastError: null,
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: createReadyBootstrap({
          nextStep: "permissions",
          organizationState: { mode: "owner", organizationName: "Team" },
          organization: { mode: "owner", organizationName: "Team" },
        }),
        startupLoading: false,
        startupError: null,
        startupBootstrap: null,
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: null,
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "",
        authPassword: "",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "owner", organizationName: "Team" },
        organizationDraftMode: "create",
        organizationName: "Team",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("You are ready");
    expect(container.textContent).not.toContain("Finish macOS permissions");
  });

  it("shows reconnect instead of ready when the app is offline", () => {
    const container = document.createElement("div");
    render(
      renderSetup({
        connected: false,
        lastError: null,
        bootstrapLoading: false,
        bootstrapError: null,
        bootstrap: createReadyBootstrap({
          organizationState: { mode: "owner", organizationName: "Team" },
          organization: { mode: "owner", organizationName: "Team" },
        }),
        startupLoading: false,
        startupError: null,
        startupBootstrap: null,
        doctorLoading: false,
        doctorError: null,
        doctor: null,
        wizardLoading: false,
        wizardSubmitting: false,
        wizardSessionId: null,
        wizardStep: null,
        wizardStatus: null,
        wizardError: null,
        wizardDraftText: "",
        wizardDraftConfirm: false,
        wizardDraftSelectIndex: 0,
        wizardDraftMultiIndexes: [],
        requestedStep: null,
        setupGuide: null,
        accountLoading: false,
        accountError: null,
        accountNotice: null,
        account: null,
        authMode: "sign-up",
        authEmail: "",
        authPassword: "",
        aiLoading: false,
        aiError: null,
        connectorsSearch: "",
        connectorsCategoryFilter: "all",
        onConnectorsSearchChange: vi.fn(),
        onConnectorsCategoryChange: vi.fn(),
        onDismissSetupGuide: vi.fn(),
        onOpenSupportUrl: vi.fn(),
        organizationLoading: false,
        organizationError: null,
        organization: { mode: "owner", organizationName: "Team" },
        organizationDraftMode: "create",
        organizationName: "Team",
        organizationInviteEmail: "",
        connectorsLoading: false,
        connectorsError: null,
        connectorCatalog: [],
        connectorAuthorizations: [],
        nativeShellLoading: false,
        nativeShellError: null,
        nativeShellState: createNativeShellState(),
        onAuthModeChange: vi.fn(),
        onAuthEmailChange: vi.fn(),
        onAuthPasswordChange: vi.fn(),
        onConnect: vi.fn(),
        onOpenWorkspace: vi.fn(),
        onOpenChannels: vi.fn(),
        onOpenSettingsAi: vi.fn(),
        onOpenSettingsMac: vi.fn(),
        onSetLaunchAtLogin: vi.fn(),
        onRequestPermission: vi.fn(),
        onDraftModeChange: vi.fn(),
        onOrganizationNameChange: vi.fn(),
        onInviteEmailChange: vi.fn(),
        onCreateOrganization: vi.fn(),
        onJoinOrganization: vi.fn(),
        onResetOrganization: vi.fn(),
        onBeginConnector: vi.fn(),
        onRevokeConnector: vi.fn(),
        onStartWizard: vi.fn(),
        onContinueWizard: vi.fn(),
        onCancelWizard: vi.fn(),
        onWizardDraftTextChange: vi.fn(),
        onWizardDraftConfirmChange: vi.fn(),
        onWizardDraftSelectIndexChange: vi.fn(),
        onWizardDraftMultiIndexesChange: vi.fn(),
        onAccountFieldChange: vi.fn(),
        onSignUpAccount: vi.fn(),
        onSignInAccount: vi.fn(),
        onRequestPasswordReset: vi.fn(),
        onBeginAiConnect: vi.fn(),
        onDisconnectAi: vi.fn(),
        onRefreshAi: vi.fn(),
        onSaveAccount: vi.fn(),
      }),
      container,
    );

    expect(container.textContent).toContain("Reconnect Alisio");
    expect(container.textContent).not.toContain("You are ready");
  });
});
