apiVersion: v1
kind: Service
metadata:
  name: alisio
  labels:
    app: alisio
spec:
  type: ClusterIP
  selector:
    app: alisio
  ports:
    - name: gateway
      port: 40705
      targetPort: 40705
      protocol: TCP
