import type { TSchema } from "@sinclair/typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesDeleteParamsSchema,
  AgentsFilesDeleteResultSchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsInstallParamsSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
} from "./agents-models-skills.js";
import {
  AlisioAiBeginConnectParamsSchema,
  AlisioAiBeginConnectResultSchema,
  AlisioAiCompleteConnectParamsSchema,
  AlisioAiDisconnectParamsSchema,
  AlisioAiGetParamsSchema,
  AlisioAiLimitsSchema,
  AlisioAiRenameProfileParamsSchema,
  AlisioAiRefreshLimitsParamsSchema,
  AlisioAiSelectProfileParamsSchema,
  AlisioAiStateSchema,
  AlisioAiUsageWindowSchema,
  AlisioAccountCompleteProfileParamsSchema,
  AlisioAccountGetParamsSchema,
  AlisioAccountPasswordResetParamsSchema,
  AlisioAccountPasswordResetResultSchema,
  AlisioAccountRecoveryEmailParamsSchema,
  AlisioAccountRecoveryEmailResultSchema,
  AlisioAccountEmailAuthBeginParamsSchema,
  AlisioAccountEmailAuthBeginResultSchema,
  AlisioAccountEmailLinkAuthCompleteParamsSchema,
  AlisioAccountEmailAuthVerifyParamsSchema,
  AlisioAccountGoogleAuthBeginParamsSchema,
  AlisioAccountGoogleAuthBeginResultSchema,
  AlisioAccountSignInParamsSchema,
  AlisioAccountSignOutParamsSchema,
  AlisioAccountSignUpParamsSchema,
  AlisioAccountResultSchema,
  AlisioAccountSessionSchema,
  AlisioAccountUpdateParamsSchema,
  AlisioBootstrapGetParamsSchema,
  AlisioModelsGetParamsSchema,
  AlisioModelsInstallParamsSchema,
  AlisioModelsInstallResultSchema,
  AlisioModelsUninstallParamsSchema,
  AlisioModelsUninstallResultSchema,
  AlisioModelsServerRemoveParamsSchema,
  AlisioModelsServerRemoveResultSchema,
  AlisioModelsServerSaveParamsSchema,
  AlisioModelsServerSaveResultSchema,
  AlisioModelsServerSelectParamsSchema,
  AlisioModelsServerSelectResultSchema,
  AlisioModelsResultSchema,
  AlisioBootstrapResultSchema,
  AlisioConnectedAccountSchema,
  AlisioConnectorAuthorizationSchema,
  AlisioConnectorDefinitionSchema,
  AlisioConnectorSummarySchema,
  AlisioConnectorsBeginParamsSchema,
  AlisioConnectorsBeginResultSchema,
  AlisioConnectorsCatalogParamsSchema,
  AlisioConnectorsCatalogResultSchema,
  AlisioConnectorsCompleteParamsSchema,
  AlisioConnectorsListParamsSchema,
  AlisioConnectorsListResultSchema,
  AlisioConnectorsRevokeParamsSchema,
  AlisioDoctorSummaryParamsSchema,
  AlisioDoctorSummaryResultSchema,
  AlisioRuntimeRestartParamsSchema,
  AlisioRuntimeRestartResultSchema,
  AlisioInstalledLocalModelSchema,
  AlisioLocalAccountProfileSchema,
  AlisioLocalModelCatalogEntrySchema,
  AlisioModelHardwareSchema,
  AlisioModelRecommendationSchema,
  AlisioModelsTargetSchema,
  AlisioLocalDeviceSessionSchema,
  AlisioLocalUserPreferencesSchema,
  AlisioOrganizationGetParamsSchema,
  AlisioSharingAuditEntrySchema,
  AlisioSharingApproveParamsSchema,
  AlisioSharingApproveResultSchema,
  AlisioSharingGetParamsSchema,
  AlisioSharingGrantSchema,
  AlisioSharingPolicySetParamsSchema,
  AlisioSharingPolicySetResultSchema,
  AlisioSharingPrincipalSchema,
  AlisioSharingRejectParamsSchema,
  AlisioSharingRejectResultSchema,
  AlisioSharingRequestParamsSchema,
  AlisioSharingRequestResultSchema,
  AlisioSharingRequestSchema,
  AlisioSharingRevokeParamsSchema,
  AlisioSharingRevokeResultSchema,
  AlisioSharingStateSchema,
  AlisioSharingTargetSchema,
  AlisioRemoteModelServerSchema,
  AlisioOrganizationSetParamsSchema,
  AlisioOrganizationStateSchema,
} from "./alisio.js";
import {
  ChannelsPairingApproveParamsSchema,
  ChannelsPairingRejectParamsSchema,
  ChannelsLogoutParamsSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  MemoryBackendSchema,
  MemoryEmbeddingStatusSchema,
  MemoryFilesDeleteParamsSchema,
  MemoryFilesDeleteResultSchema,
  MemoryFilesGetParamsSchema,
  MemoryFilesGetResultSchema,
  MemoryFilesListParamsSchema,
  MemoryFilesListResultSchema,
  MemoryFilesSetParamsSchema,
  MemoryFilesSetResultSchema,
  MemoryStatusBatchSchema,
  MemoryStatusCacheSchema,
  MemoryStatusConfigSchema,
  MemoryStatusFtsSchema,
  MemoryStatusParamsSchema,
  MemoryStatusResultSchema,
  MemoryStatusRuntimeSchema,
  MemoryStatusSourceCountSchema,
  MemoryStatusVectorSchema,
  MemorySyncParamsSchema,
  MemorySyncResultSchema,
  MemoryWorkspaceFileDocumentSchema,
  MemoryWorkspaceFileEntrySchema,
} from "./memory.js";
import {
  NodeCapabilityManifestSchema,
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
  NodeTaskEventParamsSchema,
  NodeTaskRequestEventSchema,
  NodeTaskResultParamsSchema,
  NodeTaskStartParamsSchema,
} from "./nodes.js";
import {
  PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParamsSchema,
} from "./plugin-approvals.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import {
  SessionsAbortParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCreateParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AlisioConnectedAccount: AlisioConnectedAccountSchema,
  AlisioConnectorDefinition: AlisioConnectorDefinitionSchema,
  AlisioConnectorAuthorization: AlisioConnectorAuthorizationSchema,
  AlisioConnectorSummary: AlisioConnectorSummarySchema,
  AlisioLocalAccountProfile: AlisioLocalAccountProfileSchema,
  AlisioLocalModelCatalogEntry: AlisioLocalModelCatalogEntrySchema,
  AlisioInstalledLocalModel: AlisioInstalledLocalModelSchema,
  AlisioModelHardware: AlisioModelHardwareSchema,
  AlisioModelRecommendation: AlisioModelRecommendationSchema,
  AlisioRemoteModelServer: AlisioRemoteModelServerSchema,
  AlisioModelsTarget: AlisioModelsTargetSchema,
  AlisioLocalUserPreferences: AlisioLocalUserPreferencesSchema,
  AlisioAccountSession: AlisioAccountSessionSchema,
  AlisioAiUsageWindow: AlisioAiUsageWindowSchema,
  AlisioAiLimits: AlisioAiLimitsSchema,
  AlisioAiState: AlisioAiStateSchema,
  AlisioLocalDeviceSession: AlisioLocalDeviceSessionSchema,
  AlisioOrganizationState: AlisioOrganizationStateSchema,
  AlisioSharingPrincipal: AlisioSharingPrincipalSchema,
  AlisioSharingTarget: AlisioSharingTargetSchema,
  AlisioSharingRequest: AlisioSharingRequestSchema,
  AlisioSharingGrant: AlisioSharingGrantSchema,
  AlisioSharingAuditEntry: AlisioSharingAuditEntrySchema,
  AlisioSharingState: AlisioSharingStateSchema,
  AlisioBootstrapGetParams: AlisioBootstrapGetParamsSchema,
  AlisioModelsGetParams: AlisioModelsGetParamsSchema,
  AlisioModelsInstallParams: AlisioModelsInstallParamsSchema,
  AlisioModelsInstallResult: AlisioModelsInstallResultSchema,
  AlisioModelsUninstallParams: AlisioModelsUninstallParamsSchema,
  AlisioModelsUninstallResult: AlisioModelsUninstallResultSchema,
  AlisioModelsServerSaveParams: AlisioModelsServerSaveParamsSchema,
  AlisioModelsServerSaveResult: AlisioModelsServerSaveResultSchema,
  AlisioModelsServerRemoveParams: AlisioModelsServerRemoveParamsSchema,
  AlisioModelsServerRemoveResult: AlisioModelsServerRemoveResultSchema,
  AlisioModelsServerSelectParams: AlisioModelsServerSelectParamsSchema,
  AlisioModelsServerSelectResult: AlisioModelsServerSelectResultSchema,
  AlisioModelsResult: AlisioModelsResultSchema,
  AlisioBootstrapResult: AlisioBootstrapResultSchema,
  AlisioDoctorSummaryParams: AlisioDoctorSummaryParamsSchema,
  AlisioDoctorSummaryResult: AlisioDoctorSummaryResultSchema,
  AlisioRuntimeRestartParams: AlisioRuntimeRestartParamsSchema,
  AlisioRuntimeRestartResult: AlisioRuntimeRestartResultSchema,
  AlisioAccountGetParams: AlisioAccountGetParamsSchema,
  AlisioAccountPasswordResetParams: AlisioAccountPasswordResetParamsSchema,
  AlisioAccountPasswordResetResult: AlisioAccountPasswordResetResultSchema,
  AlisioAccountRecoveryEmailParams: AlisioAccountRecoveryEmailParamsSchema,
  AlisioAccountRecoveryEmailResult: AlisioAccountRecoveryEmailResultSchema,
  AlisioAccountEmailAuthBeginParams: AlisioAccountEmailAuthBeginParamsSchema,
  AlisioAccountEmailAuthBeginResult: AlisioAccountEmailAuthBeginResultSchema,
  AlisioAccountEmailLinkAuthCompleteParams: AlisioAccountEmailLinkAuthCompleteParamsSchema,
  AlisioAccountEmailAuthVerifyParams: AlisioAccountEmailAuthVerifyParamsSchema,
  AlisioAccountGoogleAuthBeginParams: AlisioAccountGoogleAuthBeginParamsSchema,
  AlisioAccountGoogleAuthBeginResult: AlisioAccountGoogleAuthBeginResultSchema,
  AlisioAccountSignUpParams: AlisioAccountSignUpParamsSchema,
  AlisioAccountSignInParams: AlisioAccountSignInParamsSchema,
  AlisioAccountSignOutParams: AlisioAccountSignOutParamsSchema,
  AlisioAccountResult: AlisioAccountResultSchema,
  AlisioAccountCompleteProfileParams: AlisioAccountCompleteProfileParamsSchema,
  AlisioAccountUpdateParams: AlisioAccountUpdateParamsSchema,
  AlisioAiGetParams: AlisioAiGetParamsSchema,
  AlisioAiBeginConnectParams: AlisioAiBeginConnectParamsSchema,
  AlisioAiBeginConnectResult: AlisioAiBeginConnectResultSchema,
  AlisioAiCompleteConnectParams: AlisioAiCompleteConnectParamsSchema,
  AlisioAiDisconnectParams: AlisioAiDisconnectParamsSchema,
  AlisioAiRefreshLimitsParams: AlisioAiRefreshLimitsParamsSchema,
  AlisioAiRenameProfileParams: AlisioAiRenameProfileParamsSchema,
  AlisioAiSelectProfileParams: AlisioAiSelectProfileParamsSchema,
  AlisioOrganizationGetParams: AlisioOrganizationGetParamsSchema,
  AlisioOrganizationSetParams: AlisioOrganizationSetParamsSchema,
  AlisioSharingGetParams: AlisioSharingGetParamsSchema,
  AlisioSharingRequestParams: AlisioSharingRequestParamsSchema,
  AlisioSharingRequestResult: AlisioSharingRequestResultSchema,
  AlisioSharingApproveParams: AlisioSharingApproveParamsSchema,
  AlisioSharingApproveResult: AlisioSharingApproveResultSchema,
  AlisioSharingRejectParams: AlisioSharingRejectParamsSchema,
  AlisioSharingRejectResult: AlisioSharingRejectResultSchema,
  AlisioSharingRevokeParams: AlisioSharingRevokeParamsSchema,
  AlisioSharingRevokeResult: AlisioSharingRevokeResultSchema,
  AlisioSharingPolicySetParams: AlisioSharingPolicySetParamsSchema,
  AlisioSharingPolicySetResult: AlisioSharingPolicySetResultSchema,
  AlisioConnectorsCatalogParams: AlisioConnectorsCatalogParamsSchema,
  AlisioConnectorsCatalogResult: AlisioConnectorsCatalogResultSchema,
  AlisioConnectorsListParams: AlisioConnectorsListParamsSchema,
  AlisioConnectorsListResult: AlisioConnectorsListResultSchema,
  AlisioConnectorsBeginParams: AlisioConnectorsBeginParamsSchema,
  AlisioConnectorsBeginResult: AlisioConnectorsBeginResultSchema,
  AlisioConnectorsCompleteParams: AlisioConnectorsCompleteParamsSchema,
  AlisioConnectorsRevokeParams: AlisioConnectorsRevokeParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeCapabilityManifest: NodeCapabilityManifestSchema,
  NodeListParams: NodeListParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeTaskStartParams: NodeTaskStartParamsSchema,
  NodeTaskEventParams: NodeTaskEventParamsSchema,
  NodeTaskResultParams: NodeTaskResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  NodeTaskRequestEvent: NodeTaskRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  ChannelsPairingApproveParams: ChannelsPairingApproveParamsSchema,
  ChannelsPairingRejectParams: ChannelsPairingRejectParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsFilesDeleteParams: AgentsFilesDeleteParamsSchema,
  AgentsFilesDeleteResult: AgentsFilesDeleteResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  MemoryBackend: MemoryBackendSchema,
  MemoryEmbeddingStatus: MemoryEmbeddingStatusSchema,
  MemoryStatusSourceCount: MemoryStatusSourceCountSchema,
  MemoryStatusCache: MemoryStatusCacheSchema,
  MemoryStatusFts: MemoryStatusFtsSchema,
  MemoryStatusVector: MemoryStatusVectorSchema,
  MemoryStatusBatch: MemoryStatusBatchSchema,
  MemoryStatusConfig: MemoryStatusConfigSchema,
  MemoryStatusRuntime: MemoryStatusRuntimeSchema,
  MemoryStatusParams: MemoryStatusParamsSchema,
  MemoryStatusResult: MemoryStatusResultSchema,
  MemoryWorkspaceFileEntry: MemoryWorkspaceFileEntrySchema,
  MemoryWorkspaceFileDocument: MemoryWorkspaceFileDocumentSchema,
  MemoryFilesListParams: MemoryFilesListParamsSchema,
  MemoryFilesListResult: MemoryFilesListResultSchema,
  MemoryFilesGetParams: MemoryFilesGetParamsSchema,
  MemoryFilesGetResult: MemoryFilesGetResultSchema,
  MemoryFilesSetParams: MemoryFilesSetParamsSchema,
  MemoryFilesSetResult: MemoryFilesSetResultSchema,
  MemoryFilesDeleteParams: MemoryFilesDeleteParamsSchema,
  MemoryFilesDeleteResult: MemoryFilesDeleteResultSchema,
  MemorySyncParams: MemorySyncParamsSchema,
  MemorySyncResult: MemorySyncResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  PluginApprovalRequestParams: PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: PluginApprovalResolveParamsSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;

export const PROTOCOL_VERSION = 3 as const;
