export const DEFAULT_GATEWAY_PORT = 40705;
export const DEFAULT_GATEWAY_PORT_TEXT = String(DEFAULT_GATEWAY_PORT);
export const DEFAULT_LOCAL_GATEWAY_HOST = "127.0.0.1";
export const DEFAULT_LOCAL_GATEWAY_WS_URL = `ws://${DEFAULT_LOCAL_GATEWAY_HOST}:${DEFAULT_GATEWAY_PORT}`;
export const DEFAULT_LOCAL_GATEWAY_HTTP_URL = `http://${DEFAULT_LOCAL_GATEWAY_HOST}:${DEFAULT_GATEWAY_PORT}`;
