// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["memory-core-engine-runtime"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "memory-core",
    artifactBasename: "runtime-api.js",
  });
}
export const buildCanonicalMemoryStoreStatus: FacadeModule["buildCanonicalMemoryStoreStatus"] = ((
  ...args
) =>
  loadFacadeModule()["buildCanonicalMemoryStoreStatus"](
    ...args,
  )) as FacadeModule["buildCanonicalMemoryStoreStatus"];
export const getBuiltinMemoryEmbeddingProviderDoctorMetadata: FacadeModule["getBuiltinMemoryEmbeddingProviderDoctorMetadata"] =
  ((...args) =>
    loadFacadeModule()["getBuiltinMemoryEmbeddingProviderDoctorMetadata"](
      ...args,
    )) as FacadeModule["getBuiltinMemoryEmbeddingProviderDoctorMetadata"];
export const getMemorySearchManager: FacadeModule["getMemorySearchManager"] = ((...args) =>
  loadFacadeModule()["getMemorySearchManager"](...args)) as FacadeModule["getMemorySearchManager"];
export const listBuiltinAutoSelectMemoryEmbeddingProviderDoctorMetadata: FacadeModule["listBuiltinAutoSelectMemoryEmbeddingProviderDoctorMetadata"] =
  ((...args) =>
    loadFacadeModule()["listBuiltinAutoSelectMemoryEmbeddingProviderDoctorMetadata"](
      ...args,
    )) as FacadeModule["listBuiltinAutoSelectMemoryEmbeddingProviderDoctorMetadata"];
export const memoryWriteEvent: FacadeModule["memoryWriteEvent"] = ((...args) =>
  loadFacadeModule()["memoryWriteEvent"](...args)) as FacadeModule["memoryWriteEvent"];
export const MemoryIndexManager: FacadeModule["MemoryIndexManager"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["MemoryIndexManager"] as object,
) as FacadeModule["MemoryIndexManager"];
export type BuiltinMemoryEmbeddingProviderDoctorMetadata =
  FacadeEntry["types"]["BuiltinMemoryEmbeddingProviderDoctorMetadata"];
export type CanonicalMemoryStoreStatus = FacadeEntry["types"]["CanonicalMemoryStoreStatus"];
export type CanonicalStoreBackend = FacadeEntry["types"]["CanonicalStoreBackend"];
export type MemoryWriteEventResult = FacadeEntry["types"]["MemoryWriteEventResult"];
