// Narrow plugin-sdk surface for the bundled memory-core plugin.
// Keep this list additive and scoped to the bundled memory-core surface.

export { getMemorySearchManager, MemoryIndexManager } from "./memory-core-engine-runtime.js";
export {
  DEFAULT_PI_COMPACTION_RESERVE_TOKENS_FLOOR,
  emptyPluginConfigSchema,
  jsonResult,
  loadConfig,
  parseAgentSessionKey,
  parseNonNegativeByteSize,
  readNumberParam,
  readStringParam,
  resolveCronStyleNow,
  resolveDefaultAgentId,
  resolveMemorySearchConfig,
  resolveSessionAgentId,
  resolveSessionTranscriptsDirForAgent,
  resolveStateDir,
  SILENT_REPLY_TOKEN,
} from "./memory-core-host-runtime-core.js";
export type {
  AnyAgentTool,
  MemoryCitationsMode,
  MemoryFlushPlan,
  MemoryFlushPlanResolver,
  MemoryPluginRuntime,
  MemoryPromptSectionBuilder,
  AlisioPluginApi,
} from "./memory-core-host-runtime-core.js";
export type { AlisioConfig } from "../config/config.js";
export {
  colorize,
  defaultRuntime,
  formatDocsLink,
  formatErrorMessage,
  formatHelpExamples,
  isRich,
  isVerbose,
  resolveCommandSecretRefsViaGateway,
  setVerbose,
  shortenHomeInString,
  shortenHomePath,
  theme,
  withManager,
  withProgress,
  withProgressTotals,
} from "./memory-core-host-runtime-cli.js";
export {
  CANONICAL_INDEXED_MEMORY_FILE_KINDS,
  CANONICAL_MEMORY_FILE_AVAILABILITIES,
  CANONICAL_MEMORY_FILE_GROUPS,
  CANONICAL_MEMORY_FILE_KINDS,
  CANONICAL_MEMORY_KIND_DESCRIPTORS,
  CANONICAL_MEMORY_NOTE_ROLES,
  CANONICAL_MEMORY_SESSION_KINDS,
  CANONICAL_NON_INDEXED_MEMORY_FILE_KINDS,
  CANONICAL_OPERATIONAL_MEMORY_FILE_KINDS,
  CANONICAL_PERSONAL_CONTEXT_INHERITANCE_VALUES,
  CANONICAL_PERSONAL_CONTEXT_SESSION_ROLE_VALUES,
  CANONICAL_ROOT_MEMORY_FILE_NAMES,
  buildCanonicalMemoryNotePath,
  compareCanonicalMemoryFileOrder,
  getCanonicalMemoryFileAvailability,
  getCanonicalMemoryFileGroup,
  getCanonicalMemoryFileSessionKinds,
  getCanonicalMemoryFileSortRank,
  getCanonicalMemoryKindDescriptor,
  isCanonicalMemoryFileName,
  isCanonicalIndexedMemoryKind,
  isCanonicalOperationalMemoryKind,
  isDailyMemoryNoteFileName,
  isLongTermMemoryFileName,
  isMemoryNoteFileName,
  listMemoryFiles,
  listCanonicalRootMemoryFileNames,
  normalizeMemoryFileName,
  normalizeExtraMemoryPaths,
  normalizeMemoryNoteRole,
  readAgentMemoryFile,
  resolveCanonicalMemoryFileKind,
  resolveCanonicalMemoryFileMemoryRole,
  resolveMemoryBackendConfig,
  resolveMemoryNoteRole,
  slugifyMemoryNotePathComponent,
} from "./memory-core-host-runtime-files.js";
export type {
  CanonicalMemoryFileAvailability,
  CanonicalMemoryFileGroup,
  CanonicalMemoryFileKind,
  CanonicalMemoryKindDescriptor,
  CanonicalMemorySessionKind,
  CanonicalPersonalContextInheritance,
  CanonicalPersonalContextSessionRole,
  MemoryNoteRole,
  MemorySearchResult,
} from "./memory-core-host-runtime-files.js";
