export const browserCoreExamples = [
  "alisio browser status",
  "alisio browser start",
  "alisio browser stop",
  "alisio browser tabs",
  "alisio browser open https://example.com",
  "alisio browser focus abcd1234",
  "alisio browser close abcd1234",
  "alisio browser screenshot",
  "alisio browser screenshot --full-page",
  "alisio browser screenshot --ref 12",
  "alisio browser snapshot",
  "alisio browser snapshot --format aria --limit 200",
  "alisio browser snapshot --efficient",
  "alisio browser snapshot --labels",
];

export const browserActionExamples = [
  "alisio browser navigate https://example.com",
  "alisio browser resize 1280 720",
  "alisio browser click 12 --double",
  'alisio browser type 23 "hello" --submit',
  "alisio browser press Enter",
  "alisio browser hover 44",
  "alisio browser drag 10 11",
  "alisio browser select 9 OptionA OptionB",
  "alisio browser upload /tmp/alisio/uploads/file.pdf",
  'alisio browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alisio browser dialog --accept",
  'alisio browser wait --text "Done"',
  "alisio browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alisio browser console --level error",
  "alisio browser pdf",
];
